---
title: "Question 5"
output: html_document
date: "2022-12-18"
---

```{r setup, include=FALSE}
#loads data variable
load("Problem_5.RData")
R= data[,1]/data[,2]
```

```{r}
# Score
Compute_Gradient <- function(r, theta, ...){
  
  return(1/theta - 2*mean(r/(1+theta*r)))
}

# (Negative) observed information
Compute_Hessian <- function(r, theta, ...){
  
  return(1/theta^2-2*mean(r^2/(1+theta*r)^2))
}
```

```{r}

# MLE Estiamtion by Newton Raphson
Compute_MLE <- function(r, initialEstimate = NULL, precision = 1e-6){
    theta <- 1
    
  # Iteration for desired precision
  while(T){
    prev_theta = theta
    theta <- prev_theta + Compute_Hessian(r,prev_theta)^(-1) *
      Compute_Gradient(r, prev_theta)
      
    # Check for convergence
    if(abs(theta - prev_theta) < precision)
      break
  }
    
  # Retuning data
  return(theta)
      
}
```

```{r}
(theta_MLE = Compute_MLE(R))
```
Our estimate comes out to be about $\hat{\theta}\approx 1.78468$. We can then give an estimate for the standard error. We know that $$se(\hat{\theta})=\sqrt{\frac{1}{n} I^{-1}(\hat{\theta})}.$$ In part c, we calculated $$I^{-1}(\theta)=\left(\frac{1}{\theta^2}-2E\left[\frac{r^2}{(1 + \theta r)^2} \right]\right)^{-1}$$

```{r}
information = Compute_Hessian(R, theta_MLE)
sqrt(information^(-1)/length(R))
```
Thus we have that $se(\hat{\theta})\approx 0.70186$.