---
title: "Quiz 2.1"
output: html_document
date: "2022-10-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("mvnfast")
# install.packages("glmnet")
# library("mvnfast")
# library("glmnet")
```

```{r, include=FALSE}
set.seed(770025884)

N = 10
n = seq(20, 200, by = 20)
beta = c(1, 1, 1, -1, -1, -1, 0, 0, 0, 0)
rho = 0.5
Sigma = matrix(0, nrow = length(beta), ncol = length(beta))

for (i in 1:length(beta)) {
  for (j in 1:length(beta)) {
    Sigma[i, j] = rho ^ (abs(i - j))
  }
}

conf_intervals=matrix(0,ncol = 2,nrow = length(n))

MSPE_diff = rep(0,N)
for (j in 1:length(n)) {
  for (i in 1:N) {
    sig_squared = t(beta) %*% Sigma %*% beta
    
    x_train = mvnfast::rmvn(n = n[j],
                            mu = rep(0, length(beta)),
                            sigma = Sigma)
    y_train = x_train %*% beta + rnorm(n[j], sd = sqrt(sig_squared))
    
    RR_fit = glmnet::cv.glmnet(x_train, y_train, alpha = 0)
    
    x_test = mvnfast::rmvn(n = n[j]*10,
                           mu = rep(0, length(beta)),
                           sigma = Sigma)
    y_test = x_test %*% beta + rnorm(n[j]*10, sd = sqrt(sig_squared))
    
    RR_predictions = predict(RR_fit, newx = x_test, s = "lambda.min")
    LS_predictions = solve(t(x_test) %*% x_test) %*% t(x_test) %*% y_test
    
    MSPE_LS = mean((y_test - as.vector(LS_predictions)) ^ 2)
    MSPE_RR = mean((y_test - as.vector(RR_predictions)) ^ 2)
    
    MSPE_diff[i] = MSPE_LS - MSPE_RR
  }

diff_bar=mean(MSPE_diff)
diff_std=sd(MSPE_diff)

conf_intervals[j,1]=qnorm(0.025,mean=diff_bar,sd=diff_std/sqrt(N))
conf_intervals[j,2]=qnorm(0.975,mean=diff_bar,sd=diff_std/sqrt(N))

}

data.frame(n,Lower_Bound=conf_intervals[,1],Upper_Bound=conf_intervals[,2])
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```
